AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: ToDo - Every lambda its own sqs, delete one environment
Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME: !Ref MBTITABLE
        ENDPOINT_OVERRIDE: ''
        
Resources:
#Process SQS Lambdas
  LambdaProcessSQS:
    Type: AWS::Serverless::Function
    DependsOn:
      - MBTIQueue
    Properties:
      CodeUri: hello_world/
      Handler: create_db.lambda_handler
      Runtime: python3.7
      Role: !GetAtt BackendLambdaRole.Arn

  BackendLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyName: allowMessagingSQS
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - 'sqs:*'
              Resource: !GetAtt MBTIQueue.Arn
              
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: "sts:AssumeRole"
            Principal:
              Service:
                - "lambda.amazonaws.com"
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

#FRONT LAMBDAS  
#Role for put to dynamo
  LambdaSendSQSrole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
            - sts:AssumeRole
        Policies:
          - PolicyName: allowMessagingSQS
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Effect: Allow
                Action:
                  - 'sqs:*'
                Resource: !GetAtt MBTIQueue.Arn
                
  LambdaDelete:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: hello_world/
      Handler: delete.lambda_handler
      Runtime: python3.7
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref MBTIQueue
      Events:
        DeleteOrder:
          Type: Api
          Properties:
            Path: '/mbtis/{mbti_id}'
            Method: delete
  
  LambdaPost:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: hello_world/
      Handler: create.lambda_handler
      Role: !GetAtt LambdaSendSQSrole.Arn
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref MBTIQueue
      Runtime: python3.7
      Events:
        CreateOrder:
          Type: Api
          Properties:
            Path: /mbtis
            Method: post
 
  LambdaGet:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: hello_world/
      Handler: get.lambda_handler
      Runtime: python3.7
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref MBTIQueue
      Events:
        GetOrder:
          Type: Api
          Properties:
            Path: '/mbtis/{mbti_id}'
            Method: get
#BACKEND DATABASE
  MBTITABLE:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: mbtis_table
      AttributeDefinitions:
        - AttributeName: Name
          AttributeType: S
      KeySchema:
        - AttributeName: Name
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
#SQS 
  MyDeadLetterQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: DeadLetterMBTIQueue
      
  MappingLambdaMessaging:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      Enabled: true
      EventSourceArn: !GetAtt MBTIQueue.Arn
      FunctionName: !Ref LambdaProcessSQS

  MBTIQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: MBTIQueue
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt 
          - MyDeadLetterQueue
          - Arn
        maxReceiveCount: 5

#Outputs:
 # ProdDataEndpoint:
  #  Description: "API Prod stage endpoint"
   # Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"